CREATE TABLE IF NOT EXISTS payment_audits (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_no TEXT,
    alt_no TEXT,
    tracking_number TEXT,
    customer_name TEXT,
    profile_name TEXT,
    subtotal DECIMAL(10, 2),
    shipping_cost DECIMAL(10, 2),
    discount DECIMAL(10, 2),
    total DECIMAL(10, 2),
    paid_amount DECIMAL(10, 2),
    payment_provider TEXT,
    account_no TEXT,
    account_name TEXT,
    paid_at TEXT,
    sku TEXT,
    item_name TEXT,
    item_qty INTEGER,
    item_price DECIMAL(10, 2),
    grand_total DECIMAL(10, 2),
    confirmed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    discrepancy TEXT,
    audit_date DATE
);
